[config]

[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type", "center"]
set = true

[templates.hyprland]
input_path = './templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.kitty]
input_path = './templates/kitty-colors.conf'
output_path = '~/.config/kitty/colors.conf'
post_hook = 'pkill -SIGUSR1 kitty'

[templates.starship]
input_path = './templates/starship-colors.toml'
output_path = '~/.config/starship.toml'

[templates.json]
input_path = './templates/json-colors.json'
output_path = '~/.config/matugen/colors.json'

[templates.mhd-shell]
input_path = './templates/mhdshell-colors.conf'
output_path = '~/dev/mhdshell/Theme.qml'

[templates.tmux]
input_path = './templates/tmux-colors.conf'
output_path = '~/.config/tmux/tmux.conf'
post_hook = 'tmux source-file ~/.config/tmux/tmux.conf'

# [templates.qt5ct]
# input_path = './templates/qtct-colors.conf'
# output_path = '~/.config/qt5ct/colors/matugen.conf'
#
# [templates.qt6ct]
# input_path = './templates/qtct-colors.conf'
# output_path = '~/.config/qt6ct/colors/matugen.conf'
#
# [templates.gtk3]
# input_path = './templates/gtk-colors.css'
# output_path = '~/.config/gtk-3.0/colors.css'
# post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'
#
# [templates.gtk4]
# input_path = './templates/gtk-colors.css'
# output_path = '~/.config/gtk-4.0/colors.css'
#
# [templates.vesktop]
# input_path = './templates/midnight-discord.css'
# output_path = '~/.config/vesktop/themes/midnight-discord.css'
#
